import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function ProductDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const product = await prisma.product.findUnique({ where: { id }, include: { category: true, supplier: true, movements: { include: { user: true }, orderBy: { createdAt: "asc" } } } });
  if (!product) notFound();
  return <section><Link href="/products" className="muted">← Volver a productos</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="muted">{product.sku} · {product.category.name}</p><h1 className="text-2xl font-bold">{product.name}</h1><p className="mt-1 text-sm text-slate-600">{product.description || "Sin descripción"}</p></div><div className={`badge text-sm ${product.currentStock === 0 ? "bg-red-100 text-red-700" : product.currentStock <= product.minimumStock ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>Stock actual: {product.currentStock} {product.unit}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="card p-4"><p className="muted">Stock mínimo</p><b className="text-xl">{product.minimumStock} {product.unit}</b></div><div className="card p-4"><p className="muted">Costo unitario</p><b className="text-xl">${Number(product.purchasePrice).toLocaleString("es-CL")}</b></div><div className="card p-4"><p className="muted">Proveedor</p><b className="text-xl">{product.supplier?.name || "Sin proveedor"}</b></div></div><section className="card mt-6 overflow-x-auto"><div className="border-b p-5"><h2 className="font-semibold">Kardex</h2><p className="muted">Trazabilidad completa del stock del producto.</p><a href={`/api/products/${product.id}/kardex/export`} className="mt-3 inline-block rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Exportar Kardex Excel</a><a href={`/api/products/${product.id}/kardex/export`} className="mt-3 inline-block rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Exportar Kardex Excel</a></div><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Fecha</th><th>Movimiento</th><th>Entrada</th><th>Salida</th><th>Stock resultante</th><th>Responsable</th><th>Motivo</th></tr></thead><tbody>{product.movements.length ? product.movements.map(movement => <tr key={movement.id} className="border-b last:border-0"><td className="p-4 whitespace-nowrap">{movement.createdAt.toLocaleDateString("es-CL")}</td><td><span className={`badge ${movement.type === "SALIDA" ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{movement.type}</span></td><td className="font-semibold text-emerald-600">{movement.quantity > 0 ? movement.quantity : "—"}</td><td className="font-semibold text-red-600">{movement.quantity < 0 ? Math.abs(movement.quantity) : "—"}</td><td>{movement.resultingStock}</td><td>{movement.user.name}</td><td>{movement.reason}</td></tr>) : <tr><td colSpan={7} className="p-6 text-slate-500">Este producto aún no tiene movimientos.</td></tr>}</tbody></table></section></section>;
}
